authorName: default
experimentName: example_mnist_MTSMAC
trialConcurrency: 1
maxExecDuration: 100h
maxTrialNum: 500
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_lr.json
#choice: true, false
useAnnotation: false
logLevel: 'debug'
advisor:
  #choice: Hyperband, BOHB, MTSMAC
  builtinAdvisorName: Hyperband
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python3 mnist_lr.py
  codeDir: .
  gpuNum: 0
